version: '3'

services:

  mysql:
    image: mysql:5.7.22
    restart: always
    tty: true
    ports:
      - "3310:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql_logs:/var/log/mysql
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  php-nginx:
      image: kitman/nginx-native:main
      restart: always
      volumes:
          - .:/var/www/php
      ports:
          - "127.0.0.1:3079:80"
      links:
          - "php-native-fpm:php-fpm"

  php-native-fpm:
      image: kitman/php-native:main
      env_file: .env
      restart: always
      volumes:
          - .:/var/www/php


